<?php
/**
 * Copyright © Thana', Inc. All rights reserved. 
 */
 
/** @var CustomerLogin\Tracking\Block\Account\PreviousLoginData $block */
?> 
<?php if (!$block->getLastLoginTransactionInformationBeforeCurrentLogin()) : ?>
    <div class="container">
        <div class="block-title">
            <strong>Previous login data of current login</strong>
        </div>
        <div class="block-content">
        <div class="box box-previous-login-information">
            <strong class="box-title">
                <span>Login Data</span>
            </strong>
            <div class="box-content">
                <p>
                    IP Address: <?php echo $block->getPreviouslyOfCurrentLoginIpAddress(); ?><br>
                    Device Type: <?php echo $block->getPreviouslyOfCurrentLoginUserAgent(); ?><br>
                    Login Time: <?php echo $block->getPreviouslyOfCurrentLoginTime(); ?><br>

                </p>
            </div> 
        </div> 
        </div>
<?php else : ?>
	<div class="message info empty">
		<span><?php echo $block->getMessageForFirstLogin(); ?></span>
	</div>
<?php endif; ?> 
    </div>